## constants
TERMS = "terms"
TERM = "term"
TF = "term frequency"
DF = "document frequency"
INIT_TOKENS = "init_tokens"
T_INDEX = "t_index"
TF_IDF = "tf-idf"
PRESENT = "present"
ABSENT = "absent"
N11 = "n11"
N10 = "n10"
N01 = "n01"
N00 = "n00"
LIKELIHOOD_RATIO = "likelihood_ratio"
CHI_SQR = "chi_sqr"
SIMILARITY = "similarity"
J_INDEX = "j_index"
